spring:
  application:
    name: gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: BalloonDelivery
          uri: lb://BalloonDelivery
          predicates:
            - Path=/**
  profiles:
    include: private, datasource
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
  port: 8080



