spring:
  application:
    name: BalloonDelivery
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#  # sql init (data.sql)
#  sql:
#    init:
#      mode: always

logging:
  level:
    org:
      hibernate:
        SQL: debug
