spring:
  application:
    name: BalloonDelivery
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: default
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  profiles:
    include: private

logging:
  level:
    org:
      hibernate:
        SQL: debug

server:
  port: 19093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
